language: java
script: mvn clean package

addons:
  coverity_scan:
    project:
      name: "jakubuskuba/TravisTest"
      description: "Build submitted via Travis CI"
    notification_email: jakubus_kuba@o2.pl
    build_command:   "mvn clean -DskipTests=true compile"
    branch_pattern: coverity_scan